### ISSUE TITLE
It actually requires user attention

### ISSUE THREAD

**Issue by CaledoniaProject** [manwhoami/MMeTokenDecrypt#2]
The readme says no user interaction is required, but .. I got a dialog pops up, is it expected?

![screen 2016-11-07 at 17 07 18](https://cloud.githubusercontent.com/assets/1357701/20051966/aa998b5a-a50c-11e6-92d7-70823dbb74b6.jpg)

Running OSX Sierra 10.12.1

**Comment by manwhoami** [comment]
Great question. No user authentication (not interaction) is needed, I.E. No keychain login is needed. It is very easy to get a user to click "allow" because you can wrap this keychain all in a loop that continually presents the dialog until the user accepts (almost guaranteed). Also, if you have access to the GUI but not the keychain password, you can cut out having to even get the user to click allow (you can click it).

**Comment by CaledoniaProject** [comment]
Thanks.
