### ISSUE TITLE
Stops working on MacOS Sierra

### ISSUE THREAD

**Issue by spdustin** [manwhoami/MMeTokenDecrypt#4]
Attempted to use this to recover my own tokens for a little Find My iPhone hackery, but received this error using `/usr/bin/python` indicating that `NSData` can't be imported from `Foundation`. I also learned that `NSPropertyListSerialization` can't be imported from `Foundation` either. Nor can they be imported from `AppKit`

```bash
> /usr/bin/python --version
```

```
Python 2.7.10
```

```bash
> /usr/bin/python MMeDecrypt.py
```

```
Traceback (most recent call last):
  File "MMeDecrypt.py", line 2, in <module>
    from Foundation import NSData, NSPropertyListSerialization
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/Foundation/__init__.py", line 8, in <module>
    import objc
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/__init__.py", line 28, in <module>
    from objc._bridgesupport import *
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_bridgesupport.py", line 13, in <module>
    import pkg_resources
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 31, in <module>
    import token
  File "/Users/me/Downloads/MMeDecrypt.py", line 2, in <module>
    from Foundation import NSData, NSPropertyListSerialization
ImportError: cannot import name NSData
```

**Comment by manwhoami** [comment]
Peculiar. From what I understand of PyObjc, Foundation / NSData should be installed on all macOS versions of Python. Rather than troubleshoot why you're getting this issue, we can do a little workaround. The NSData module is a little overkill, it is like using an airplane to travel a mile. It does make processing the decrypted binary plist in python pretty easy though, which is why it is used. On line 33, instead of creating binToPlist, you can just print out the contents of decryptedBinary. There will be some binary junk in there (it is a binary plist), but you should be able to see the dictionary for the tokens, including that for findmyiphone.
 
Also, for FMI hackery, the FMI tokens that this program extracts can be used only to CHANGE location data (e.g. using poof), but cannot be used to GET location data (macOS has no app for getting the location of FMI, so it does not have the token needed for this. macOS does have software to set its location in iCloud, so it does have the token needed for this - if Apple ever ships a FMI app with macOS, then I will update this program to extract those tokens to GET location). If you want a token to GET location data, you need to MITM the FMIP app on your iOS device, and get the "Forever" auth token that is transmitted when you update the location of your devices.
 
Let me know how it goes

**Comment by spdustin** [comment]
Turns out I absolutely must use the system `python`, which solved that problem.

Now, it doesn't appear to retrieve the iCloud creds. Running `security find-generic-password -ws 'iCloud'` from a terminal returns nothing.

**Comment by NateJackDev** [comment]
Question @manwhoami who maintains the https://github.com/Trietptm-on-Security/Bella
