### ISSUE TITLE
How to use these tokens?

### ISSUE THREAD

**Issue by thealex626** [manwhoami/MMeTokenDecrypt#6]
Hello. How to further use the tokens with iCloud? Can I login into icloud using extracted tokens?

**Comment by manwhoami** [comment]
These tokens are the functional equivalent of usernames and passwords. 

They can be used to access iCloud backup containers if the tokens were generated in the past ~15 hours. 

They can be used to access iCloud photos, iCloud contacts, Find my Friends, Find my iPhone, iCloud Notes, etc... regardless of when they were generated. Due to the nature of 2FA, these tokens will also bypass 2FA on an iCloud account (many of which are enabled with 2FA by default nowadays). There are a variety of tools (some open source (see my other repos) and some not), to access this data.
